[versions]
activation = "1.1.1"
assertj = "3.27.6"
async-http-client = "3.0.5"
commons-cli = "1.11.0"
commons-lang3 = "3.20.0"
commons-text = "1.15.0"
jaxb-api = "4.0.4"
jsr173_api = "1.0"
junit-jupiter = "6.0.1"
junit-platform = "6.0.1"
lombok = "1.18.42"
netty = "4.2.9.Final"
saxon = "9.1.0.8"
shadow = "9.3.0"
slf4j = "2.0.17"
sun-jaxb = "4.0.6"
waena = "0.21.1"
xml-commons-resolver = "1.1"
xmlbeans = "5.3.0"

[libraries]
activation = { module = "javax.activation:activation", version.ref = "activation" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
async-http-client = { module = "org.asynchttpclient:async-http-client", version.ref = "async-http-client" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxb-api" }
jaxb-core = { module = "com.sun.xml.bind:jaxb-core", version.ref = "sun-jaxb" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "sun-jaxb" }
jsr173_api = { module = "javax.xml.bind:jsr173_api", version.ref = "jsr173_api" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
netty = { module = "io.netty:netty-all", version.ref = "netty" }
saxon = { module = "net.sourceforge.saxon:saxon", version.ref = "saxon" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
xml-commons-resolver = { module = "org.dspace.xmlui.xml:xml-commons-resolver", version.ref = "xml-commons-resolver" }
xmlbeans = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeans" }


[bundles]
jaxb = [ "jaxb-api", "jaxb-core", "jaxb-impl" ]
junit-runtime = [ "junit-jupiter-engine", "junit-platform-launcher" ]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
waena-published = { id = "com.github.rahulsom.waena.published", version.ref = "waena" }
waena-root = { id = "com.github.rahulsom.waena.root", version.ref = "waena" }
